// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/match_evaluator.proto

package match_evaluator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for MatchEvaluator service

func NewMatchEvaluatorEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for MatchEvaluator service

type MatchEvaluatorService interface {
	ToEval(ctx context.Context, in *ToEvalReq, opts ...client.CallOption) (*ToEvalRsp, error)
}

type matchEvaluatorService struct {
	c    client.Client
	name string
}

func NewMatchEvaluatorService(name string, c client.Client) MatchEvaluatorService {
	return &matchEvaluatorService{
		c:    c,
		name: name,
	}
}

func (c *matchEvaluatorService) ToEval(ctx context.Context, in *ToEvalReq, opts ...client.CallOption) (*ToEvalRsp, error) {
	req := c.c.NewRequest(c.name, "MatchEvaluator.ToEval", in)
	out := new(ToEvalRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MatchEvaluator service

type MatchEvaluatorHandler interface {
	ToEval(context.Context, *ToEvalReq, *ToEvalRsp) error
}

func RegisterMatchEvaluatorHandler(s server.Server, hdlr MatchEvaluatorHandler, opts ...server.HandlerOption) error {
	type matchEvaluator interface {
		ToEval(ctx context.Context, in *ToEvalReq, out *ToEvalRsp) error
	}
	type MatchEvaluator struct {
		matchEvaluator
	}
	h := &matchEvaluatorHandler{hdlr}
	return s.Handle(s.NewHandler(&MatchEvaluator{h}, opts...))
}

type matchEvaluatorHandler struct {
	MatchEvaluatorHandler
}

func (h *matchEvaluatorHandler) ToEval(ctx context.Context, in *ToEvalReq, out *ToEvalRsp) error {
	return h.MatchEvaluatorHandler.ToEval(ctx, in, out)
}
